version: "3.1"
services:
   mysql:
      image: mysql:latest
      container_name: mysql
      ports:
         - 3307:3306
      environment:
         MYSQL_ALLOW_EMPTY_PASSWORD: True
         MYSQL_ROOT_USERNAME: root
         MYSQL_DATABASE: kubernetes
      networks:
         - springboot
      volumes:
         - application:/var/lib/mysql

   spring:
      image: spring-boot:latest
      container_name: spring-application
      ports:
         - 8082:8081
      environment:
         MYSQL_HOST: mysql
         MYSQL_USER: root
         MYSQL_PORT: 3306
      links:
         - mysql
      networks:
         - springboot
networks:
   springboot:
      name: springboot
      driver: bridge
volumes:
   application:
      external: true
