apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  labels: 
    app: mysql
    tier: database
spec:
  resources:
    requests:
      storage: 1G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
